//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyTimeTable.Resx {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyTimeTable.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   일정추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddSchedule {
            get {
                return ResourceManager.GetString("AddSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타임매니저과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   취소하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   내용과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Contents {
            get {
                return ResourceManager.GetString("Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DayofWeek {
            get {
                return ResourceManager.GetString("DayofWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   편집과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   종료 시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   금과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   홈화면과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   내용을 입력하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InsertContents {
            get {
                return ResourceManager.GetString("InsertContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제목을 입력하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InsertTitle {
            get {
                return ResourceManager.GetString("InsertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   반복 여부과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Iteration {
            get {
                return ResourceManager.GetString("Iteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   분과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   월과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   월과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   야간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   내용없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Nocontent {
            get {
                return ResourceManager.GetString("Nocontent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   반복하지 않음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotIterative {
            get {
                return ResourceManager.GetString("NotIterative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제목없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Notitle {
            get {
                return ResourceManager.GetString("Notitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   준비중입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Prepearing {
            get {
                return ResourceManager.GetString("Prepearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   토과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장할 날짜과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ScheduleDate {
            get {
                return ResourceManager.GetString("ScheduleDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일정 시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ScheduleTime {
            get {
                return ResourceManager.GetString("ScheduleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   색깔과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SelectColor {
            get {
                return ResourceManager.GetString("SelectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시작 시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   목과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제목과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   화과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수정하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주일과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Weekday {
            get {
                return ResourceManager.GetString("Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주말과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Weekend {
            get {
                return ResourceManager.GetString("Weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   년도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
